// Every JSON Schema of the API, in one place. They are used for three things at once:
//   1. request validation (Ajv, see validation.js), so the documented limits ARE the enforced limits;
//   2. the OpenAPI 3.1 document behind Swagger UI (openapi.js);
//   3. standalone schemas at GET /schemas/<Name>.json for contract tests in Playwright.
//
// House rules (checked by test/docs.test.js):
//   - every schema node has a `description` and a non-empty `examples` array (plural; never `example`);
//   - strings have a maxLength (or an enum/const/pattern), arrays a maxItems;
//   - objects say `additionalProperties: false` (unknown fields are rejected, not silently dropped);
//   - no $ref: shared pieces are JS constants, so every schema is self-contained.

import { MISSING_CARD_ID, SEED_CARDS, SEED_DECKS, cardId, deckId } from './seed.js';
import { ERROR_CODES } from './errors.js';

export const UUID_PATTERN = '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
export const TOKEN_PATTERN = '^tcg_[A-Za-z0-9_-]{43}$';
export const DIFFICULTIES = ['beginner', 'intermediate', 'advanced', 'expert'];
export const MAX_DECK_CARDS = 40;
export const MAX_COPIES = 3;

/** A stored deck as the API returns it: with the computed totalCards (never stored). */
export function withTotal(deck) {
  const { id, name, theme, description, difficulty, cards, createdAt, updatedAt } = deck;
  const totalCards = cards.reduce((sum, c) => sum + c.quantity, 0);
  return { id, name, theme, description, difficulty, cards, totalCards, createdAt, updatedAt };
}

// ---------- building blocks ----------

const uuid = (description, examples) => ({
  type: 'string', format: 'uuid', pattern: UUID_PATTERN, description, examples,
});

const timestamp = (description) => ({
  type: 'string', format: 'date-time', maxLength: 30, readOnly: true,
  description: `${description} UTC, ISO 8601 with milliseconds. Set by the server; ignored if you send it.`,
  examples: ['2026-01-01T00:01:00.000Z'],
});

const text = (description, minLength, maxLength, examples, extra = {}) => ({
  type: 'string', minLength, maxLength, description, examples, ...extra,
});

const integer = (description, minimum, maximum, examples, extra = {}) => ({
  type: 'integer', minimum, maximum, description, examples, ...extra,
});

// ---------- cards ----------

export const AttributeValue = {
  title: 'AttributeValue',
  description: 'The value of one card attribute: a string (1-60 characters), a number, true/false, '
    + 'or - when there are several values - an array of 1-10 strings or numbers. Nested objects are not allowed.',
  type: ['string', 'number', 'boolean', 'array'],
  minLength: 1,
  maxLength: 60,
  minItems: 1,
  maxItems: 10,
  items: {
    type: ['string', 'number'],
    minLength: 1,
    maxLength: 60,
    description: 'One of several values, e.g. one element of a dual-element card.',
    examples: ['Tide', 3],
  },
  examples: ['Creature', 5, true, ['Tide', 'Lumen']],
};

const cardProperties = {
  id: { ...uuid('Id of the card, generated by the server (read-only). On PUT, if you send it, it must equal ?id.', [cardId(1)]), readOnly: true },
  name: text('Name printed on the card. Unique among all cards, ignoring upper/lower case (409 NAME_TAKEN).', 1, 80,
    ['Cinderwing Drake']),
  description: text('Rules or flavour text. Defaults to an empty string.', 0, 500,
    ['Flying. When it enters, deal 1 damage to each Gale creature.'], { default: '' }),
  imageUrl: text('Absolute http(s) link to the card art. The seed links use the reserved .example domain, so they are placeholders that never load.', 1, 500,
    ['https://images.glyphwild.example/cards/cinderwing-drake.png'], { format: 'uri', pattern: '^https?://' }),
  attributes: {
    type: 'object',
    description: 'Free-form game attributes as key/value pairs; a value can be an array when there are several. '
      + 'Conventional keys: type (Creature | Spell | Relic | Terrain), element (Ember | Tide | Gale | Stone | Lumen | Umbra), '
      + 'cost, points, rarity (Common | Uncommon | Rare | Mythic), keywords, legendary. '
      + 'At most 12 keys; key names start with a lowercase letter and contain only letters and digits (max 30). Defaults to {}.',
    maxProperties: 12,
    propertyNames: { pattern: '^[a-z][a-zA-Z0-9]{0,29}$', description: 'Attribute name, e.g. element.', examples: ['element'] },
    additionalProperties: AttributeValue,
    default: {},
    examples: [{ type: 'Creature', element: ['Tide', 'Lumen'], cost: 4, points: 4, rarity: 'Uncommon', keywords: ['Ward'] }],
  },
  dropRate: {
    type: 'number', exclusiveMinimum: 0, maximum: 1,
    description: 'Chance of pulling the card from a booster pack, as a fraction: 0.05 means 5%. Must be above 0 and at most 1.',
    examples: [0.06],
  },
  createdAt: timestamp('When the card was created.'),
  updatedAt: timestamp('When the card was last changed; always increases on PUT.'),
};

export const Card = {
  title: 'Card',
  description: 'A Glyphwild card, as returned by the API.',
  type: 'object',
  additionalProperties: false,
  required: Object.keys(cardProperties),
  properties: cardProperties,
  examples: [SEED_CARDS[1]],
};

export const CardInput = {
  title: 'CardInput',
  description: 'Body of POST /cards and PUT /cards. It is the same shape as Card, so you can send back what GET returned: '
    + 'id, createdAt and updatedAt are optional and ignored (on PUT, id must equal ?id). name, imageUrl and dropRate are required. '
    + 'PUT replaces the whole card: optional fields you leave out go back to their defaults.',
  type: 'object',
  additionalProperties: false,
  required: ['name', 'imageUrl', 'dropRate'],
  properties: cardProperties,
  examples: [{
    name: 'Brine Hatchling',
    description: 'A small Tide creature for testing.',
    imageUrl: 'https://images.glyphwild.example/cards/brine-hatchling.png',
    attributes: { type: 'Creature', element: 'Tide', cost: 1, points: 1, rarity: 'Common' },
    dropRate: 0.4,
  }],
};

// ---------- decks ----------

export const DeckCard = {
  title: 'DeckCard',
  description: 'One line of a deck list: which card, and how many copies.',
  type: 'object',
  additionalProperties: false,
  required: ['cardId', 'quantity'],
  properties: {
    cardId: uuid('Id of an existing card.', [cardId(3)]),
    quantity: integer(`Number of copies, 1 to ${MAX_COPIES}.`, 1, MAX_COPIES, [3]),
  },
  examples: [{ cardId: cardId(3), quantity: 3 }],
};

const deckProperties = {
  id: { ...uuid('Id of the deck, generated by the server (read-only). On PUT, if you send it, it must equal ?id.', [deckId(1)]), readOnly: true },
  name: text('Deck name. Unique among all decks, ignoring upper/lower case (409 NAME_TAKEN).', 1, 80, ['Ashes & Embers']),
  theme: text("The deck's plan or archetype, free text.", 1, 60, ['Aggressive Ember burn']),
  description: text('How to play the deck. Defaults to an empty string.', 0, 500,
    ['Cheap Ember creatures and burn spells that try to win before turn six.'], { default: '' }),
  difficulty: {
    type: 'string', enum: DIFFICULTIES,
    description: 'How hard the deck is to play well (lowercase). Sorting by difficulty uses this order, not the alphabet.',
    examples: ['beginner'],
  },
  cards: {
    type: 'array',
    description: `The deck list, in the order you send it. Rules: each cardId at most once, every card must exist, `
      + `quantities add up to at most ${MAX_DECK_CARDS}. Defaults to [].`,
    maxItems: MAX_DECK_CARDS,
    items: DeckCard,
    default: [],
    examples: [[{ cardId: cardId(3), quantity: 3 }, { cardId: cardId(4), quantity: 2 }]],
  },
  totalCards: integer(`Sum of all quantities (read-only, computed by the server; ignored if you send it).`, 0, MAX_DECK_CARDS, [10],
    { readOnly: true }),
  createdAt: timestamp('When the deck was created.'),
  updatedAt: timestamp('When the deck was last changed; always increases on PUT.'),
};

export const Deck = {
  title: 'Deck',
  description: 'A Glyphwild deck, as returned by the API.',
  type: 'object',
  additionalProperties: false,
  required: Object.keys(deckProperties),
  properties: deckProperties,
  examples: [withTotal(SEED_DECKS[0])],
};

export const DeckInput = {
  title: 'DeckInput',
  description: 'Body of POST /decks and PUT /decks. The same shape as Deck, so you can send back what GET returned: '
    + 'id, totalCards, createdAt and updatedAt are optional and ignored (on PUT, id must equal ?id). '
    + 'name, theme and difficulty are required. PUT replaces the whole deck.',
  type: 'object',
  additionalProperties: false,
  required: ['name', 'theme', 'difficulty'],
  properties: deckProperties,
  examples: [{
    name: 'Tide Starter',
    theme: 'Simple Tide creatures',
    description: 'A small deck for practice.',
    difficulty: 'beginner',
    cards: [{ cardId: cardId(7), quantity: 3 }, { cardId: cardId(9), quantity: 2 }],
  }],
};

// ---------- lists ----------

const page = (itemSchema, name, example) => ({
  title: `${name}Page`,
  description: `One page of ${name.toLowerCase()} search results.`,
  type: 'object',
  additionalProperties: false,
  required: ['items', 'page', 'pageSize', 'total', 'totalPages'],
  properties: {
    items: { type: 'array', maxItems: 50, items: itemSchema, description: `The ${name.toLowerCase()}s on this page (can be empty).`, examples: [[example]] },
    page: integer('The page number you asked for (starts at 1).', 1, 10000, [1]),
    pageSize: integer('The page size you asked for.', 1, 50, [10]),
    total: integer('How many items match the filters, over all pages.', 0, 1000000, [25]),
    totalPages: integer('ceil(total / pageSize); 0 when nothing matches.', 0, 1000000, [3]),
  },
  examples: [{ items: [example], page: 1, pageSize: 10, total: 1, totalPages: 1 }],
});

export const CardPage = page(Card, 'Card', SEED_CARDS[1]);
export const DeckPage = page(Deck, 'Deck', withTotal(SEED_DECKS[0]));

// ---------- auth ----------

export const LoginRequest = {
  title: 'LoginRequest',
  description: 'Credentials of one of the two built-in users (see the start-up banner or the docs landing page).',
  type: 'object',
  additionalProperties: false,
  required: ['username', 'password'],
  properties: {
    username: text('Username (case-sensitive).', 1, 50, ['admin']),
    password: text('Password.', 1, 100, ['admin123'], { writeOnly: true }),
  },
  examples: [{ username: 'admin', password: 'admin123' }],
};

const role = {
  type: 'string', enum: ['admin', 'viewer'],
  description: 'admin can read and write; viewer can only read (writes return 403).',
  examples: ['admin'],
};

export const User = {
  title: 'User',
  description: 'The logged-in user.',
  type: 'object',
  additionalProperties: false,
  required: ['username', 'role'],
  properties: { username: text('Username.', 1, 50, ['admin']), role },
  examples: [{ username: 'admin', role: 'admin' }],
};

export const LoginResponse = {
  title: 'LoginResponse',
  description: "A new random bearer token. Send it as 'Authorization: Bearer <token>'. Tokens live in server memory: they end on logout, expiry or a server restart.",
  type: 'object',
  additionalProperties: false,
  required: ['token', 'tokenType', 'expiresIn', 'expiresAt', 'user'],
  properties: {
    token: {
      type: 'string', pattern: TOKEN_PATTERN,
      description: "Opaque random token (not a JWT): 'tcg_' followed by 43 URL-safe characters.",
      examples: ['tcg_3q2-7wEzkQdJY0v1b9Hn5cXkPp8sLrTmUa6fGiVoWjE'],
    },
    tokenType: { type: 'string', const: 'Bearer', description: 'Always Bearer.', examples: ['Bearer'] },
    expiresIn: integer('Seconds until the token expires (TOKEN_TTL_SECONDS).', 1, 2592000, [86400]),
    expiresAt: { ...timestamp('When the token expires.'), description: 'When the token expires (UTC, ISO 8601).' },
    user: User,
  },
  examples: [{
    token: 'tcg_3q2-7wEzkQdJY0v1b9Hn5cXkPp8sLrTmUa6fGiVoWjE', tokenType: 'Bearer', expiresIn: 86400,
    expiresAt: '2026-10-01T10:00:00.000Z', user: { username: 'admin', role: 'admin' },
  }],
};

export const Me = {
  title: 'Me',
  description: 'Who the presented token belongs to.',
  type: 'object',
  additionalProperties: false,
  required: ['username', 'role', 'expiresAt'],
  properties: {
    username: text('Username.', 1, 50, ['viewer']),
    role,
    expiresAt: { ...timestamp('When the token expires.'), description: 'When this token expires (UTC, ISO 8601).' },
  },
  examples: [{ username: 'viewer', role: 'viewer', expiresAt: '2026-10-01T10:00:00.000Z' }],
};

// ---------- system ----------

export const Health = {
  title: 'Health',
  description: 'Liveness information plus the active teaching-knob settings.',
  type: 'object',
  additionalProperties: false,
  required: ['status', 'name', 'version', 'startedAt', 'uptimeSeconds', 'data', 'settings'],
  properties: {
    status: { type: 'string', const: 'ok', description: 'Always ok when the API answers.', examples: ['ok'] },
    name: { type: 'string', const: 'glyphwild-tcg-api', description: 'Identifies this API (useful when something else uses the port).', examples: ['glyphwild-tcg-api'] },
    version: text('API version (semver).', 1, 20, ['1.0.0']),
    startedAt: { ...timestamp('When the server started.'), description: 'When the server started (UTC).' },
    uptimeSeconds: integer('Seconds since start.', 0, 1e9, [42]),
    data: {
      type: 'object', additionalProperties: false, required: ['cards', 'decks'],
      description: 'How many cards and decks are stored right now.',
      properties: {
        cards: integer('Number of cards.', 0, 1e6, [25]),
        decks: integer('Number of decks.', 0, 1e6, [6]),
      },
      examples: [{ cards: 25, decks: 6 }],
    },
    settings: {
      type: 'object', additionalProperties: false,
      required: ['latencyMs', 'chaosRate', 'teachingHeaders', 'tokenTtlSeconds', 'resetOnStart'],
      description: 'Active settings (from environment variables / compose.yaml).',
      properties: {
        latencyMs: integer('LATENCY_MS: extra delay on /cards and /decks requests.', 0, 60000, [0]),
        chaosRate: { type: 'number', minimum: 0, maximum: 1, description: 'CHAOS_RATE: share of successful /cards and /decks requests that fail with 500.', examples: [0] },
        teachingHeaders: { type: 'boolean', description: 'TEACHING_HEADERS: whether X-Delay-Ms / X-Chaos-* request headers are honoured.', examples: [true] },
        tokenTtlSeconds: integer('TOKEN_TTL_SECONDS: token lifetime.', 1, 2592000, [86400]),
        resetOnStart: { type: 'boolean', description: 'RESET_ON_START: whether seed data is restored on every start.', examples: [true] },
      },
      examples: [{ latencyMs: 0, chaosRate: 0, teachingHeaders: true, tokenTtlSeconds: 86400, resetOnStart: true }],
    },
  },
  examples: [{
    status: 'ok', name: 'glyphwild-tcg-api', version: '1.0.0', startedAt: '2026-09-30T08:00:00.000Z', uptimeSeconds: 42,
    data: { cards: 25, decks: 6 }, settings: { latencyMs: 0, chaosRate: 0, teachingHeaders: true, tokenTtlSeconds: 86400, resetOnStart: true },
  }],
};

export const ResetResult = {
  title: 'ResetResult',
  description: 'The seed data was restored. Tokens stay valid.',
  type: 'object',
  additionalProperties: false,
  required: ['message', 'cards', 'decks', 'resetAt'],
  properties: {
    message: text('Human-readable confirmation.', 1, 200, ['Seed data restored.']),
    cards: integer('Cards after the reset.', 0, 1000, [25]),
    decks: integer('Decks after the reset.', 0, 1000, [6]),
    resetAt: { ...timestamp('When the reset happened.'), description: 'When the reset happened (UTC).' },
  },
  examples: [{ message: 'Seed data restored.', cards: 25, decks: 6, resetAt: '2026-09-30T08:00:00.000Z' }],
};

export const SchemaIndex = {
  title: 'SchemaIndex',
  description: 'The standalone JSON Schemas you can download for contract tests.',
  type: 'object',
  additionalProperties: false,
  required: ['items'],
  properties: {
    items: {
      type: 'array', maxItems: 50,
      description: 'One entry per schema.',
      items: {
        type: 'object', additionalProperties: false, required: ['name', 'url', 'description'],
        description: 'A downloadable schema.',
        properties: {
          name: text('Schema name.', 1, 50, ['Card']),
          url: text('Where to download it (relative to the API).', 1, 100, ['/schemas/Card.json']),
          description: text('What it describes.', 1, 500, ['A Glyphwild card, as returned by the API.']),
        },
        examples: [{ name: 'Card', url: '/schemas/Card.json', description: 'A Glyphwild card, as returned by the API.' }],
      },
      examples: [[{ name: 'Card', url: '/schemas/Card.json', description: 'A Glyphwild card, as returned by the API.' }]],
    },
  },
  examples: [{ items: [{ name: 'Card', url: '/schemas/Card.json', description: 'A Glyphwild card, as returned by the API.' }] }],
};

// ---------- errors ----------

export const ErrorDetail = {
  title: 'ErrorDetail',
  description: 'One problem with the request.',
  type: 'object',
  additionalProperties: false,
  required: ['field', 'rule', 'message'],
  properties: {
    field: text('Where the problem is: query.<name>, body.<path> (e.g. body.cards[1].quantity), header.<name>, or body for the whole body.', 1, 200,
      ['body.dropRate']),
    rule: text('Which rule failed: a JSON Schema keyword (required, type, minLength, maxLength, minimum, maximum, exclusiveMinimum, pattern, format, enum, '
      + 'additionalProperties, minItems, maxItems, maxProperties, propertyNames) or an API rule (singleValue, requiredWith, idMatchesQuery, uniqueCardIds, maxTotalCards, '
      + 'minNotAboveMax, cardExists, unique, notInUse, mediaType). Assert on this, not on the message text.', 1, 50, ['maximum']),
    message: text('Human-readable explanation (may change between versions).', 1, 500, ['must be <= 1']),
  },
  examples: [{ field: 'body.dropRate', rule: 'maximum', message: 'must be <= 1' }],
};

export const ErrorResponse = {
  title: 'ErrorResponse',
  description: 'Every 4xx/5xx response has this shape. Assert on status, code and details[].field / details[].rule.',
  type: 'object',
  additionalProperties: false,
  required: ['status', 'code', 'message', 'details', 'requestId'],
  properties: {
    status: integer('The HTTP status code, repeated in the body.', 400, 599, [400]),
    code: { type: 'string', enum: Object.keys(ERROR_CODES), description: 'Machine-readable error code (see the table on the docs landing page).', examples: ['VALIDATION_ERROR'] },
    message: text('Human-readable summary; for validation errors it joins all details.', 1, 5000, ['body.dropRate must be <= 1']),
    details: {
      type: 'array', maxItems: 200, items: ErrorDetail,
      description: 'Every individual problem (empty when there is nothing to list), sorted by field.',
      examples: [[{ field: 'body.dropRate', rule: 'maximum', message: 'must be <= 1' }]],
    },
    requestId: text('Same value as the X-Request-Id response header; the server log line has it too.', 1, 64,
      ['3f0c2a8e-5d1b-4c7e-9a44-0b7f1f6d2c10']),
  },
  examples: [{
    status: 404, code: 'NOT_FOUND', message: `No card has the id '${MISSING_CARD_ID}'.`, details: [],
    requestId: '3f0c2a8e-5d1b-4c7e-9a44-0b7f1f6d2c10',
  }],
};

// ---------- query strings (the OpenAPI parameters are generated from these) ----------

const pagingProperties = {
  order: { type: 'string', enum: ['asc', 'desc'], default: 'asc', description: 'Sort direction. Ties are always broken by id, ascending.', examples: ['desc'] },
  page: integer('Page number, starting at 1. A page past the end returns an empty items array.', 1, 10000, [2], { default: 1 }),
  pageSize: integer('Items per page, 1 to 50.', 1, 50, [5], { default: 10 }),
};

export const IdQuery = {
  title: 'IdQuery',
  description: 'The id of one resource.',
  type: 'object',
  additionalProperties: false,
  required: ['id'],
  properties: { id: uuid('Id of the resource: a lowercase UUID. Required; to list or search use the /search endpoint.', [cardId(1)]) },
  examples: [{ id: cardId(1) }],
};

export const NoQuery = {
  title: 'NoQuery',
  description: 'This endpoint takes no query parameters.',
  type: 'object',
  additionalProperties: false,
  properties: {},
  examples: [{}],
};

export const CardSearchQuery = {
  title: 'CardSearchQuery',
  description: 'Card search filters. All are optional and combine with AND.',
  type: 'object',
  additionalProperties: false,
  properties: {
    name: text('Cards whose name CONTAINS this text, ignoring case (accents are not ignored: zephyr does not find Zéphyr).', 1, 80, ['drake']),
    type: text('Cards whose attributes.type EQUALS this, ignoring case.', 1, 60, ['Spell']),
    element: text('Cards whose attributes.element equals this (ignoring case), or contains it when the element is an array.', 1, 60, ['Lumen']),
    minDropRate: { type: 'number', minimum: 0, maximum: 1, description: 'dropRate >= this.', examples: [0.3] },
    maxDropRate: { type: 'number', minimum: 0, maximum: 1, description: 'dropRate <= this. Must not be below minDropRate.', examples: [0.02] },
    minPoints: integer('attributes.points >= this (cards without points never match).', 0, 99, [7]),
    maxPoints: integer('attributes.points <= this. Must not be below minPoints.', 0, 99, [2]),
    sortBy: { type: 'string', enum: ['name', 'dropRate', 'createdAt'], default: 'name', description: 'Field to sort by.', examples: ['dropRate'] },
    ...pagingProperties,
  },
  examples: [{ element: 'Lumen', sortBy: 'dropRate', order: 'desc', page: 1, pageSize: 10 }],
};

export const DeckSearchQuery = {
  title: 'DeckSearchQuery',
  description: 'Deck search filters. All are optional and combine with AND.',
  type: 'object',
  additionalProperties: false,
  properties: {
    name: text('Decks whose name CONTAINS this text, ignoring case.', 1, 80, ['tide']),
    theme: text('Decks whose theme CONTAINS this text, ignoring case.', 1, 60, ['control']),
    difficulty: { type: 'string', enum: DIFFICULTIES, description: 'Decks with exactly this difficulty.', examples: ['beginner'] },
    cardId: uuid('Decks that contain this card (useful before deleting a card).', [cardId(1)]),
    sortBy: {
      type: 'string', enum: ['name', 'difficulty', 'totalCards', 'createdAt'], default: 'name',
      description: 'Field to sort by. difficulty sorts beginner < intermediate < advanced < expert.', examples: ['difficulty'],
    },
    ...pagingProperties,
  },
  examples: [{ difficulty: 'beginner', sortBy: 'totalCards', order: 'desc' }],
};

// ---------- registry ----------

/** The schemas published at /schemas/<Name>.json and under components.schemas. */
export const PUBLIC_SCHEMAS = {
  Card, CardInput, AttributeValue, CardPage, Deck, DeckInput, DeckCard, DeckPage,
  LoginRequest, LoginResponse, User, Me, Health, ResetResult, SchemaIndex, ErrorResponse, ErrorDetail,
};
